In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset = pd.read_csv('/content/Bank_data.csv')
display(dataset)

,Customer_ID,Age,Gender,Marital_Status,Employment_Type,Annual_Income,Loan_Amount,Loan_Term_Months,Credit_Score,Number_of_Dependents,...,Unwanted_Column_13,Unwanted_Column_14,Unwanted_Column_15,Unwanted_Column_16,Unwanted_Column_17,Unwanted_Column_18,Unwanted_Column_19,Unwanted_Column_20,Unwanted_Column_21,Unwanted_Column_22
0,CUST100000,56.0,NaN,Marrid,Unemployed,50000,10000,NaN,450,NaN,...,?,?,error,,NaN,error,NaN,0.11811040559076358,NaN,NaN
1,CUST100001,69.0,Mal,Marrid,Salaried,50000,10000,12,Bad,0,...,,823,,error,,error,?,NaN,NaN,NaN
2,CUST100002,46.0,Other,Singl,Salaried,NaN,NaN,NaN,NaN,0,...,NaN,0.47522270615276174,NaN,7978,0.20436277293007032,NaN,error,0.11811040559076358,NaN,NaN
3,CUST100003,32.0,NaN,Widowed,Unemployed,"1,20,000",₹200000,12 months,450,1,...,NaN,?,NaN,error,NaN,0.12114014160842657,?,NaN,Unknown,?
4,CUST100004,60.0,Female,Single,Self-Employed,200000,10000,48,NaN,3,...,error,ExtraValue,Unknown,?,error,4665,ExtraValue,ExtraValue,Unknown,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15745,CUST113584,40.0,Male,Married,Salaried,₹80000,NaN,12 months,450,Unknown,...,7697,NaN,error,Unknown,NaN,NaN,NaN,,NaN,
15746,CUST112144,49.0,Female,Married,Self-Employed,₹80000,300k,12 months,900,2,...,Unknown,NaN,NaN,,ExtraValue,4665,error,0.11811040559076358,ExtraValue,NaN
15747,CUST114397,54.0,NaN,Singl,Salaried,50000,₹200000,NaN,900,0,...,0.32904090262240415,NaN,9815,NaN,error,ExtraValue,ExtraValue,1331,?,error
15748,CUST108787,30.0,Male,Divorced,Self-Employed,50000,₹200000,12,300,2,...,NaN,,Unknown,NaN,NaN,error,0.15253320238847856,?,?,error
15749,CUST114191,29.0,Femlae,Divorced,Salaried,50000,10000,12 months,900,4,...,ExtraValue,ExtraValue,9815,,3957,NaN,error,NaN,ExtraValue,NaN

In [ ]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [ ]:
dataset.shape

(15750, 61)

In [ ]:
dataset.head(20)

,Customer_ID,Age,Gender,Marital_Status,Employment_Type,Annual_Income,Loan_Amount,Loan_Term_Months,Credit_Score,Number_of_Dependents,Past_Defaults,Loan_Purpose,Current_Residence_Years,Default,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,Unwanted_Column_1,Unwanted_Column_2,Unwanted_Column_3,Unwanted_Column_4,Unwanted_Column_5,Unwanted_Column_6,Unwanted_Column_7,Unwanted_Column_8,Unwanted_Column_9,Unwanted_Column_10,Unwanted_Column_11,Unwanted_Column_12,Unwanted_Column_13,Unwanted_Column_14,Unwanted_Column_15,Unwanted_Column_16,Unwanted_Column_17,Unwanted_Column_18,Unwanted_Column_19,Unwanted_Column_20,Unwanted_Column_21,Unwanted_Column_22
0,CUST100000,56.0,NaN,Marrid,Unemployed,50000,10000,NaN,450,NaN,1,Education,16,Y,650673,?,Cash loans,NaN,NaN,?,700k,NaN,₹5000,"1,20,000",Pensioner,High,Married,Owned,-11220,-13419,IT staff,2,2.0,Tuesday,12,Govt,0.8,0.7,0.3,NaN,0.34603598087973664,NaN,NaN,0.4645068696337057,ExtraValue,?,0.6020525900553526,NaN,0.3370550949739738,0.702980230963849,2021,?,?,error,,NaN,error,NaN,0.11811040559076358,NaN,NaN
1,CUST100001,69.0,Mal,Marrid,Salaried,50000,10000,12,Bad,0,2,Business,16,Y,272165,?,Cash loans,Y,Y,0,900000,₹200000,1000,"1,20,000",Workng,High,Separated,NaN,-12092,-12490,Drivr,3,NaN,NaN,12,Med,0.8,NaN,0.6,6101,error,1763,NaN,NaN,0.5594043846983144,,NaN,0.4000104955379503,NaN,Unknown,NaN,,823,,error,,error,?,NaN,NaN,NaN
2,CUST100002,46.0,Other,Singl,Salaried,NaN,NaN,NaN,NaN,0,2,Shopping,11,YES,438093,?,RL,NaN,NaN,2,NaN,₹200000,7k,50000,Businessman,Secondary,NaN,Rent,-19822,-7838,IT staff,5,NaN,Wed,0,Business,0.8,0.9,NaN,6101,NaN,NaN,0.530113780541859,NaN,error,Unknown,Unknown,NaN,?,NaN,ExtraValue,NaN,0.47522270615276174,NaN,7978,0.20436277293007032,NaN,error,0.11811040559076358,NaN,NaN
3,CUST100003,32.0,NaN,Widowed,Unemployed,"1,20,000",₹200000,12 months,450,1,0,Personal,1,Yes,109000,1,Revolving loans,N,NO,0,900000,NaN,₹5000,50000,Pensioner,Incomplete Higher,Single,Owned,-13087,-11719,Laborer,2,1.0,Wed,12,Business,NaN,0.9,NaN,?,0.34603598087973664,ExtraValue,,,NaN,0.11269983119887728,NaN,,NaN,,NaN,NaN,?,NaN,error,NaN,0.12114014160842657,?,NaN,Unknown,?
4,CUST100004,60.0,Female,Single,Self-Employed,200000,10000,48,NaN,3,?,Personal,2,Y,802383,?,CL,NaN,YES,?,NaN,₹200000,1000,50000,Working,Higher,Married,Owned,-24318,-545,Accountant,4,NaN,NaN,NaN,Govt,NaN,NaN,NaN,ExtraValue,ExtraValue,1763,,NaN,0.5594043846983144,6317,ExtraValue,NaN,NaN,NaN,2021,error,ExtraValue,Unknown,?,error,4665,ExtraValue,ExtraValue,Unknown,NaN
5,CUST100005,25.0,Other,Married,Salaried,100k,150000,12,Bad,4,NaN,Business,10,Y,433198,0,Cash loans,YES,NaN,1,NaN,300000,₹5000,NaN,Businessman,Academic degree,Widow,NaN,-18658,-8740,Drivr,4,2.0,Mon,15,Med,0.1,0.2,Error,NaN,?,?,?,error,NaN,,NaN,Unknown,ExtraValue,NaN,,?,0.47522270615276174,Unknown,NaN,Unknown,NaN,5454,NaN,ExtraValue,error
6,CUST100006,38.0,Mal,Widowed,NaN,200000,NaN,12,NaN,2,NaN,NaN,19,YES,771238,NaN,RL,YES,YES,1,900000,300000,6000,₹900000,Businessman,Academic degree,Single,Owned,-19829,-213,Laborer,5,2.0,Tuesday,5,Med,0.8,?,Error,NaN,NaN,ExtraValue,0.530113780541859,error,ExtraValue,,,NaN,?,3374,Unknown,NaN,error,NaN,error,ExtraValue,0.12114014160842657,error,1331,Unknown,ExtraValue
7,CUST100007,56.0,NaN,Single,Jobless,NaN,₹200000,48,NaN,1,NaN,Personal,27,No,665094,0,RL,NO,NO,1,₹500000,300000,NaN,"1,20,000",Student,NaN,Married,Owned,-11903,-1103,Manager,4,1.0,Wed,15,School,0.1,0.7,0.3,6101,0.34603598087973664,0.6611700369337448,error,Unknown,error,Unknown,ExtraValue,NaN,ExtraValue,NaN,ExtraValue,NaN,NaN,ExtraValue,NaN,3957,?,Unknown,1331,?,Unknown
8,CUST100008,36.0,Male,Single,NaN,100k,10000,36,300,2,2,Shopping,3,YES,860100,1,CL,NO,N,?,"1,000,000",500k,7k,₹900000,Working,Secondary,Widow,Mortgage,-20903,-4731,NaN,4,2.0,Friday,5,School,NaN,NaN,0.6,0.1489849966307667,ExtraValue,Unknown,0.530113780541859,ExtraValue,0.5594043846983144,?,error,,NaN,ExtraValue,?,error,Unknown,Unknown,Unknown,NaN,NaN,?,ExtraValue,NaN,Unknown
9,CUST100009,40.0,NaN,Widowed,Salaried,₹80000,300k,60,700,1,NaN,Business,25,N,258745,0,RL,NaN,YES,2,900000,NaN,6000,"1,20,000",Workng,Academic degree,Single,NaN,-15221,-12802,Manager,4,3.0,Tuesday,0,NaN,0.5,NaN,Error,6101,ExtraValue,NaN,0.530113780541859,,?,NaN,4174,NaN,error,error,ExtraValue,ExtraValue,NaN,9815,ExtraValue,?,Unknown,ExtraValue,Unknown,0.15077349854867528,?
10,CUST100010,28.0,NaN,Divorced,Unemployed,₹80000,150000,48,900,Unknown,0,Shopping,2,No,598150,?,CL,N,Y,?,"1,000,000",NaN,7k,₹900000,Pensioner,Secondary,Single,NaN,-12382,-8935,NaN,4,3.0,Tuesday,15,Private,0.5,?,0.3,0.1489849966307667,NaN,,?,Unknown,Unknown,0.11269983119887728,NaN,?,NaN,,NaN,?,?,0.18341173614242723,NaN,error,Unknown,0.15253320238847856,error,NaN,5054
11,CUST100011,28.0,Femlae,Widowed,Self-Employed,200000,150000,60,300,Unknown,2,Education,7,No,942304,?,Cash loans,NO,YES,2,700k,₹200000,₹5000,"1,20,000",Working,Incomplete Higher,Separated,Rented,-8141,-8455,Laborer,4,NaN,Wed,NaN,NaN,NaN,0.9,0.3,NaN,error,1763,error,7696,318,6317,,ExtraValue,NaN,NaN,,,error,error,NaN,NaN,NaN,NaN,Unknown,0.15077349854867528,0.18391361005044948
12,CUST100012,41.0,NaN,Marrid,Salaried,"1,20,000",₹200000,12 months,900,3,1,Education,19,Y,667533,NaN,RL,Y,YES,?,900000,₹200000,6000,50000,Student,NaN,Single,NaN,-7196,-6661,Accountant,4,NaN,Wed,?,Business,NaN,NaN,NaN,NaN,NaN,?,0.530113780541859,?,NaN,NaN,NaN,Unknown,ExtraValue,0.702980230963849,Unknown,0.32904090262240415,NaN,Unknown,NaN,NaN,error,NaN,Unknown,ExtraValue,?
13,CUST100013,150.0,Mal,NaN,Unemployed,50000,150000,12,450,4,?,NaN,24,NaN,699193,0,RL,YES,NO,2,₹500000,₹200000,NaN,₹900000,Workng,High,Married,Rent,-9468,-10425,Laborer,1,1.0,Tuesday,NaN,Business,0.5,0.7,0.3,?,,error,NaN,Unknown,318,6317,?,,?,,?,NaN,Unknown,9815,Unknown,0.20436277293007032,0.12114014160842657,Unknown,?,?,NaN
14,CUST100014,53.0,Male,Singl,Jobless,₹80000,₹200000,12,700,1,1,Business,24,No,251601,0,RL,YES,N,0,NaN,1000000,6000,NaN,Pensioner,Academic degree,NaN,Rented,-7689,-11427,NaN,1,2.0,Thur,20,Med,0.1,0.9,0.3,NaN,?,?,0.530113780541859,?,318,error,,,2293,3374,2021,7697,NaN,,7978,NaN,NaN,NaN,NaN,?,NaN
15,CUST100015,57.0,Mal,Marrid,Retired,NaN,150000,36,700,NaN,1,Education,3,Yes,514326,0,Cash loans,Y,NaN,?,NaN,₹200000,6000,"1,20,000",Workng,High,Separated,Mortgage,-10535,-11124,IT staff,4,1.0,Wed,0,Med,NaN,0.7,0.4,6101,,Unknown,NaN,?,NaN,error,Unknown,2827,ExtraValue,0.702980230963849,NaN,NaN,error,NaN,error,3957,0.12114014160842657,NaN,NaN,?,error
16,CUST100016,41.0,Female,Single,Jobless,"1,20,000",10000,12,700,1,?,Home,3,Yes,531645,1,CL,NaN,N,NaN,₹500000,NaN,1000,50000,NaN,Higher,Widow,Rented,-23126,-8801,NaN,4,2.0,Wed,20,Private,0.8,0.9,NaN,0.1489849966307667,6127,,0.530113780541859,NaN,?,error,,2827,2293,ExtraValue,2021,ExtraValue,NaN,NaN,NaN,ExtraValue,?,?,Unknown,NaN,error
17,CUST100017,20.0,Other,Single,Jobless,"1,20,000",₹200000,48,300,4,?,Home,10,Yes,442102,NaN,CL,Y,NO,?,900000,1000000,6000,"1,20,000",Working,Incomplete Higher,Widow,Rent,-7842,-394,IT staff,3,NaN,Tuesday,10,Private,NaN,0.2,0.3,0.1489849966307667,Unknown,ExtraValue,0.530113780541859,NaN,Unknown,Unknown,,,ExtraValue,3374,Unknown,7697,0.47522270615276174,error,,0.20436277293007032,Unknown,Unknown,NaN,,5054
18,CUST100018,39.0,NaN,Married,Self-Employed,100k,150000,12 months,Bad,1,NaN,Car,18,N,204493,0,CL,NO,N,2,900000,1000000,6000,NaN,Working,NaN,Widow,Mortgage,-9835,-5470,Manager,4,3.0,NaN,15,School,0.1,?,0.4,,ExtraValue,Unknown,911,ExtraValue,ExtraValue,?,error,,NaN,Unknown,?,NaN,?,,,?,NaN,NaN,NaN,ExtraValue,NaN
19,CUST100019,150.0,Femlae,Single,Salaried,₹80000,10000,60,450,0,NaN,Business,29,Y,990434,1,RL,NaN,Y,2,₹500000,1000000,1000,"1,20,000",Working,Incomplete Higher,Single,Rented,-9759,-8845,Laborer,4,1.0,Mon,?,Business,NaN,0.2,0.4,ExtraValue,NaN,NaN,NaN,ExtraValue,ExtraValue,,NaN,NaN,?,NaN,Unknown,NaN,NaN,Unknown,0.09289252183373609,3957,?,error,NaN,ExtraValue,0.18391361005044948

In [ ]:
dataset.describe()

,Age,Current_Residence_Years,SK_ID_CURR,DAYS_BIRTH,DAYS_EMPLOYED,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,EXT_SOURCE_1
count,15449.000000,15750.000000,15750.000000,15750.000000,15750.000000,15750.000000,11899.000000,9517.000000
mean,44.264742,14.525333,551982.580063,-16035.809587,-7486.953333,3.005651,2.009581,0.466838
std,21.410577,8.680826,259156.732876,5191.822934,4325.167903,1.416154,0.814276,0.287108
min,-5.000000,0.000000,100077.000000,-24999.000000,-15000.000000,1.000000,1.000000,0.100000
25%,30.000000,7.000000,327897.000000,-20551.750000,-11269.750000,2.000000,1.000000,0.100000
50%,43.000000,15.000000,554029.000000,-16071.000000,-7431.000000,3.000000,2.000000,0.500000
75%,57.000000,22.000000,775903.250000,-11526.000000,-3742.000000,4.000000,3.000000,0.800000
max,150.000000,29.000000,999986.000000,-7002.000000,-1.000000,5.000000,3.000000,0.800000

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15750 entries, 0 to 15749
Data columns (total 61 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Customer_ID                 15750 non-null  object
 1   Age                         15449 non-null  float64
 2   Gender                      13103 non-null  object
 3   Marital_Status              13463 non-null  object
 4   Employment_Type             13064 non-null  object
 5   Annual_Income               13089 non-null  object
 6   Loan_Amount                 12642 non-null  object
 7   Loan_Term_Months            13555 non-null  object
 8   Credit_Score                13109 non-null  object
 9   Number_of_Dependents        13456 non-null  object
 10  Past_Defaults               12540 non-null  object
 11  Loan_Purpose                13498 non-null  object
 12  Current_Residence_Years     15750 non-null  int64
 13  Default                     13530 non-null  object
 14  SK_ID_CURR                  15750 non-null  int64
 15  TARGET                      11894 non-null  object
 16  NAME_CONTRACT_TYPE          15750 non-null  object
 17  FLAG_OWN_CAR                12594 non-null  object
 18  FLAG_OWN_REALTY             12605 non-null  object
 19  CNT_CHILDREN                13177 non-null  object
 20  AMT_INCOME_TOTAL            12547 non-null  object
 21  AMT_CREDIT                  12681 non-null  object
 22  AMT_ANNUITY                 12601 non-null  object
 23  AMT_GOODS_PRICE             11766 non-null  object
 24  NAME_INCOME_TYPE            13125 non-null  object
 25  NAME_EDUCATION_TYPE         13138 non-null  object
 26  NAME_FAMILY_STATUS          12533 non-null  object
 27  NAME_HOUSING_TYPE           12604 non-null  object
 28  DAYS_BIRTH                  15750 non-null  int64
 29  DAYS_EMPLOYED               15750 non-null  int64
 30  OCCUPATION_TYPE             13440 non-null  object
 31  CNT_FAM_MEMBERS             15750 non-null  int64
 32  REGION_RATING_CLIENT        11899 non-null  float64
 33  WEEKDAY_APPR_PROCESS_START  13085 non-null  object
 34  HOUR_APPR_PROCESS_START     13758 non-null  object
 35  ORGANIZATION_TYPE           13131 non-null  object
 36  EXT_SOURCE_1                9517 non-null   float64
 37  EXT_SOURCE_2                12654 non-null  object
 38  EXT_SOURCE_3                12645 non-null  object
 39  Unwanted_Column_1           11021 non-null  object
 40  Unwanted_Column_2           11074 non-null  object
 41  Unwanted_Column_3           11081 non-null  object
 42  Unwanted_Column_4           11017 non-null  object
 43  Unwanted_Column_5           10981 non-null  object
 44  Unwanted_Column_6           10982 non-null  object
 45  Unwanted_Column_7           11020 non-null  object
 46  Unwanted_Column_8           11006 non-null  object
 47  Unwanted_Column_9           10958 non-null  object
 48  Unwanted_Column_10          10954 non-null  object
 49  Unwanted_Column_11          10987 non-null  object
 50  Unwanted_Column_12          10998 non-null  object
 51  Unwanted_Column_13          11022 non-null  object
 52  Unwanted_Column_14          11021 non-null  object
 53  Unwanted_Column_15          10996 non-null  object
 54  Unwanted_Column_16          11005 non-null  object
 55  Unwanted_Column_17          11007 non-null  object
 56  Unwanted_Column_18          11062 non-null  object
 57  Unwanted_Column_19          11034 non-null  object
 58  Unwanted_Column_20          11126 non-null  object
 59  Unwanted_Column_21          11065 non-null  object
 60  Unwanted_Column_22          11076 non-null  object
dtypes: float64(3), int64(5), object(53)
memory usage: 7.3+ MB

In [ ]:
dataset.tail(5)

,Customer_ID,Age,Gender,Marital_Status,Employment_Type,Annual_Income,Loan_Amount,Loan_Term_Months,Credit_Score,Number_of_Dependents,Past_Defaults,Loan_Purpose,Current_Residence_Years,Default,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,Unwanted_Column_1,Unwanted_Column_2,Unwanted_Column_3,Unwanted_Column_4,Unwanted_Column_5,Unwanted_Column_6,Unwanted_Column_7,Unwanted_Column_8,Unwanted_Column_9,Unwanted_Column_10,Unwanted_Column_11,Unwanted_Column_12,Unwanted_Column_13,Unwanted_Column_14,Unwanted_Column_15,Unwanted_Column_16,Unwanted_Column_17,Unwanted_Column_18,Unwanted_Column_19,Unwanted_Column_20,Unwanted_Column_21,Unwanted_Column_22
15745,CUST113584,40.0,Male,Married,Salaried,₹80000,NaN,12 months,450,Unknown,1,Personal,22,N,266556,?,Revolving loans,YES,YES,?,NaN,1000000,1000,NaN,Working,Academic degree,Single,Mortgage,-21545,-5246,Laborer,1,2.0,Friday,0,Govt,0.5,0.7,0.6,NaN,,?,?,NaN,error,NaN,NaN,error,NaN,NaN,NaN,7697,NaN,error,Unknown,NaN,NaN,NaN,,NaN,
15746,CUST112144,49.0,Female,Married,Self-Employed,₹80000,300k,12 months,900,2,NaN,Personal,25,No,464849,1,Revolving loans,Y,NO,1,700k,₹200000,1000,₹900000,Working,High,NaN,Rent,-9203,-10810,IT staff,4,NaN,Tuesday,15,School,NaN,0.7,0.3,6101,Unknown,1763,ExtraValue,NaN,318,,Unknown,,NaN,error,error,Unknown,NaN,NaN,,ExtraValue,4665,error,0.11811040559076358,ExtraValue,NaN
15747,CUST114397,54.0,NaN,Singl,Salaried,50000,₹200000,NaN,900,0,?,Home,9,Y,940143,NaN,Cash loans,NO,NaN,NaN,₹500000,₹200000,6000,50000,Pensioner,Incomplete Higher,Single,Mortgage,-10683,-9534,NaN,3,2.0,Mon,15,Med,NaN,0.9,NaN,NaN,ExtraValue,0.6611700369337448,0.530113780541859,?,,NaN,?,,Unknown,error,NaN,0.32904090262240415,NaN,9815,NaN,error,ExtraValue,ExtraValue,1331,?,error
15748,CUST108787,30.0,Male,Divorced,Self-Employed,50000,₹200000,12,300,2,2,NaN,22,Y,109213,NaN,CL,NO,N,0,"1,000,000",NaN,NaN,NaN,NaN,Incomplete Higher,Married,Mortgage,-18183,-14833,Driver,3,2.0,Tuesday,NaN,School,0.8,0.7,Error,NaN,?,Unknown,NaN,error,Unknown,NaN,ExtraValue,NaN,,,NaN,NaN,,Unknown,NaN,NaN,error,0.15253320238847856,?,?,error
15749,CUST114191,29.0,Femlae,Divorced,Salaried,50000,10000,12 months,900,4,?,Car,6,No,817216,0,Cash loans,NaN,YES,2,₹500000,500k,NaN,50000,Pensioner,Secondary,Married,NaN,-13348,-11854,IT staff,5,NaN,Thur,15,Govt,0.1,?,0.6,ExtraValue,6127,?,0.530113780541859,NaN,,0.11269983119887728,ExtraValue,NaN,2293,NaN,?,ExtraValue,ExtraValue,9815,,3957,NaN,error,NaN,ExtraValue,NaN

In [ ]:
(dataset.isnull().sum()/len(dataset))*100

Customer_ID                    0.000000
Age                            1.911111
Gender                        16.806349
Marital_Status                14.520635
Employment_Type               17.053968
Annual_Income                 16.895238
Loan_Amount                   19.733333
Loan_Term_Months              13.936508
Credit_Score                  16.768254
Number_of_Dependents          14.565079
Past_Defaults                 20.380952
Loan_Purpose                  14.298413
Current_Residence_Years        0.000000
Default                       14.095238
SK_ID_CURR                     0.000000
TARGET                        24.482540
NAME_CONTRACT_TYPE             0.000000
FLAG_OWN_CAR                  20.038095
FLAG_OWN_REALTY               19.968254
CNT_CHILDREN                  16.336508
AMT_INCOME_TOTAL              20.336508
AMT_CREDIT                    19.485714
AMT_ANNUITY                   19.993651
AMT_GOODS_PRICE               25.295238
NAME_INCOME_TYPE              16.666667
NAME_EDUCATION_TYPE           16.584127
NAME_FAMILY_STATUS            20.425397
NAME_HOUSING_TYPE             19.974603
DAYS_BIRTH                     0.000000
DAYS_EMPLOYED                  0.000000
OCCUPATION_TYPE               14.666667
CNT_FAM_MEMBERS                0.000000
REGION_RATING_CLIENT          24.450794
WEEKDAY_APPR_PROCESS_START    16.920635
HOUR_APPR_PROCESS_START       12.647619
ORGANIZATION_TYPE             16.628571
EXT_SOURCE_1                  39.574603
EXT_SOURCE_2                  19.657143
EXT_SOURCE_3                  19.714286
Unwanted_Column_1             30.025397
Unwanted_Column_2             29.688889
Unwanted_Column_3             29.644444
Unwanted_Column_4             30.050794
Unwanted_Column_5             30.279365
Unwanted_Column_6             30.273016
Unwanted_Column_7             30.031746
Unwanted_Column_8             30.120635
Unwanted_Column_9             30.425397
Unwanted_Column_10            30.450794
Unwanted_Column_11            30.241270
Unwanted_Column_12            30.171429
Unwanted_Column_13            30.019048
Unwanted_Column_14            30.025397
Unwanted_Column_15            30.184127
Unwanted_Column_16            30.126984
Unwanted_Column_17            30.114286
Unwanted_Column_18            29.765079
Unwanted_Column_19            29.942857
Unwanted_Column_20            29.358730
Unwanted_Column_21            29.746032
Unwanted_Column_22            29.676190
dtype: float64

In [ ]:
dataset.duplicated().sum()

np.int64(750)

In [ ]:
dataset.head(5)

,Customer_ID,Age,Gender,Marital_Status,Employment_Type,Annual_Income,Loan_Amount,Loan_Term_Months,Credit_Score,Number_of_Dependents,Past_Defaults,Loan_Purpose,Current_Residence_Years,Default,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,Unwanted_Column_1,Unwanted_Column_2,Unwanted_Column_3,Unwanted_Column_4,Unwanted_Column_5,Unwanted_Column_6,Unwanted_Column_7,Unwanted_Column_8,Unwanted_Column_9,Unwanted_Column_10,Unwanted_Column_11,Unwanted_Column_12,Unwanted_Column_13,Unwanted_Column_14,Unwanted_Column_15,Unwanted_Column_16,Unwanted_Column_17,Unwanted_Column_18,Unwanted_Column_19,Unwanted_Column_20,Unwanted_Column_21,Unwanted_Column_22
0,CUST100000,56.0,NaN,Marrid,Unemployed,50000,10000,NaN,450,NaN,1,Education,16,Y,650673,?,Cash loans,NaN,NaN,?,700k,NaN,₹5000,"1,20,000",Pensioner,High,Married,Owned,-11220,-13419,IT staff,2,2.0,Tuesday,12,Govt,0.8,0.7,0.3,NaN,0.34603598087973664,NaN,NaN,0.4645068696337057,ExtraValue,?,0.6020525900553526,NaN,0.3370550949739738,0.702980230963849,2021,?,?,error,,NaN,error,NaN,0.11811040559076358,NaN,NaN
1,CUST100001,69.0,Mal,Marrid,Salaried,50000,10000,12,Bad,0,2,Business,16,Y,272165,?,Cash loans,Y,Y,0,900000,₹200000,1000,"1,20,000",Workng,High,Separated,NaN,-12092,-12490,Drivr,3,NaN,NaN,12,Med,0.8,NaN,0.6,6101,error,1763,NaN,NaN,0.5594043846983144,,NaN,0.4000104955379503,NaN,Unknown,NaN,,823,,error,,error,?,NaN,NaN,NaN
2,CUST100002,46.0,Other,Singl,Salaried,NaN,NaN,NaN,NaN,0,2,Shopping,11,YES,438093,?,RL,NaN,NaN,2,NaN,₹200000,7k,50000,Businessman,Secondary,NaN,Rent,-19822,-7838,IT staff,5,NaN,Wed,0,Business,0.8,0.9,NaN,6101,NaN,NaN,0.530113780541859,NaN,error,Unknown,Unknown,NaN,?,NaN,ExtraValue,NaN,0.47522270615276174,NaN,7978,0.20436277293007032,NaN,error,0.11811040559076358,NaN,NaN
3,CUST100003,32.0,NaN,Widowed,Unemployed,"1,20,000",₹200000,12 months,450,1,0,Personal,1,Yes,109000,1,Revolving loans,N,NO,0,900000,NaN,₹5000,50000,Pensioner,Incomplete Higher,Single,Owned,-13087,-11719,Laborer,2,1.0,Wed,12,Business,NaN,0.9,NaN,?,0.34603598087973664,ExtraValue,,,NaN,0.11269983119887728,NaN,,NaN,,NaN,NaN,?,NaN,error,NaN,0.12114014160842657,?,NaN,Unknown,?
4,CUST100004,60.0,Female,Single,Self-Employed,200000,10000,48,NaN,3,?,Personal,2,Y,802383,?,CL,NaN,YES,?,NaN,₹200000,1000,50000,Working,Higher,Married,Owned,-24318,-545,Accountant,4,NaN,NaN,NaN,Govt,NaN,NaN,NaN,ExtraValue,ExtraValue,1763,,NaN,0.5594043846983144,6317,ExtraValue,NaN,NaN,NaN,2021,error,ExtraValue,Unknown,?,error,4665,ExtraValue,ExtraValue,Unknown,NaN

In [ ]:
dataset.columns = dataset.columns.str.lower().str.strip()

In [ ]:
dataset['age'] = dataset['age'].fillna(dataset['age'].median()).astype(int)

In [ ]:
dataset['age'].isna().sum()

np.int64(0)

In [ ]:
dataset.head(5)

,customer_id,age,gender,marital_status,employment_type,annual_income,loan_amount,loan_term_months,credit_score,number_of_dependents,past_defaults,loan_purpose,current_residence_years,default,sk_id_curr,target,name_contract_type,flag_own_car,flag_own_realty,cnt_children,amt_income_total,amt_credit,amt_annuity,amt_goods_price,name_income_type,name_education_type,name_family_status,name_housing_type,days_birth,days_employed,occupation_type,cnt_fam_members,region_rating_client,weekday_appr_process_start,hour_appr_process_start,organization_type,ext_source_1,ext_source_2,ext_source_3,unwanted_column_1,unwanted_column_2,unwanted_column_3,unwanted_column_4,unwanted_column_5,unwanted_column_6,unwanted_column_7,unwanted_column_8,unwanted_column_9,unwanted_column_10,unwanted_column_11,unwanted_column_12,unwanted_column_13,unwanted_column_14,unwanted_column_15,unwanted_column_16,unwanted_column_17,unwanted_column_18,unwanted_column_19,unwanted_column_20,unwanted_column_21,unwanted_column_22
0,CUST100000,56,NaN,Marrid,Unemployed,50000,10000,NaN,450,NaN,1,Education,16,Y,650673,?,Cash loans,NaN,NaN,?,700k,NaN,₹5000,"1,20,000",Pensioner,High,Married,Owned,-11220,-13419,IT staff,2,2.0,Tuesday,12,Govt,0.8,0.7,0.3,NaN,0.34603598087973664,NaN,NaN,0.4645068696337057,ExtraValue,?,0.6020525900553526,NaN,0.3370550949739738,0.702980230963849,2021,?,?,error,,NaN,error,NaN,0.11811040559076358,NaN,NaN
1,CUST100001,69,Mal,Marrid,Salaried,50000,10000,12,Bad,0,2,Business,16,Y,272165,?,Cash loans,Y,Y,0,900000,₹200000,1000,"1,20,000",Workng,High,Separated,NaN,-12092,-12490,Drivr,3,NaN,NaN,12,Med,0.8,NaN,0.6,6101,error,1763,NaN,NaN,0.5594043846983144,,NaN,0.4000104955379503,NaN,Unknown,NaN,,823,,error,,error,?,NaN,NaN,NaN
2,CUST100002,46,Other,Singl,Salaried,NaN,NaN,NaN,NaN,0,2,Shopping,11,YES,438093,?,RL,NaN,NaN,2,NaN,₹200000,7k,50000,Businessman,Secondary,NaN,Rent,-19822,-7838,IT staff,5,NaN,Wed,0,Business,0.8,0.9,NaN,6101,NaN,NaN,0.530113780541859,NaN,error,Unknown,Unknown,NaN,?,NaN,ExtraValue,NaN,0.47522270615276174,NaN,7978,0.20436277293007032,NaN,error,0.11811040559076358,NaN,NaN
3,CUST100003,32,NaN,Widowed,Unemployed,"1,20,000",₹200000,12 months,450,1,0,Personal,1,Yes,109000,1,Revolving loans,N,NO,0,900000,NaN,₹5000,50000,Pensioner,Incomplete Higher,Single,Owned,-13087,-11719,Laborer,2,1.0,Wed,12,Business,NaN,0.9,NaN,?,0.34603598087973664,ExtraValue,,,NaN,0.11269983119887728,NaN,,NaN,,NaN,NaN,?,NaN,error,NaN,0.12114014160842657,?,NaN,Unknown,?
4,CUST100004,60,Female,Single,Self-Employed,200000,10000,48,NaN,3,?,Personal,2,Y,802383,?,CL,NaN,YES,?,NaN,₹200000,1000,50000,Working,Higher,Married,Owned,-24318,-545,Accountant,4,NaN,NaN,NaN,Govt,NaN,NaN,NaN,ExtraValue,ExtraValue,1763,,NaN,0.5594043846983144,6317,ExtraValue,NaN,NaN,NaN,2021,error,ExtraValue,Unknown,?,error,4665,ExtraValue,ExtraValue,Unknown,NaN

In [ ]:
dataset['gender'] = dataset['gender'].str.strip().str.lower()

In [ ]:
dataset['gender'] = dataset['gender'].replace({
    'male': 'male',
    'mal': 'male',
    'female': 'female',
    'fem': 'female',
    'femlae':'female',
    'other': 'other'
})

In [ ]:
dataset['age'].unique()

array([ 56,  69,  46,  32,  60,  25,  38,  36,  40,  28,  41, 150,  53,
        57,  20,  39,  19,  61,  47,  55,  50,  29,  42,  66,  44,  59,
        45,  33,  64,  68,  43,  54,  24,  26,  35,  21,  31,  67,  37,
        52,  34,  23,  -5,  51,  27,  48,  65,  62,  58,  18,  22,  30,
        49,  63])

In [ ]:
dataset.head(5)

,customer_id,age,gender,marital_status,employment_type,annual_income,loan_amount,loan_term_months,credit_score,number_of_dependents,past_defaults,loan_purpose,current_residence_years,default,sk_id_curr,target,name_contract_type,flag_own_car,flag_own_realty,cnt_children,amt_income_total,amt_credit,amt_annuity,amt_goods_price,name_income_type,name_education_type,name_family_status,name_housing_type,days_birth,days_employed,occupation_type,cnt_fam_members,region_rating_client,weekday_appr_process_start,hour_appr_process_start,organization_type,ext_source_1,ext_source_2,ext_source_3,unwanted_column_1,unwanted_column_2,unwanted_column_3,unwanted_column_4,unwanted_column_5,unwanted_column_6,unwanted_column_7,unwanted_column_8,unwanted_column_9,unwanted_column_10,unwanted_column_11,unwanted_column_12,unwanted_column_13,unwanted_column_14,unwanted_column_15,unwanted_column_16,unwanted_column_17,unwanted_column_18,unwanted_column_19,unwanted_column_20,unwanted_column_21,unwanted_column_22
0,CUST100000,56,NaN,Marrid,Unemployed,50000,10000,NaN,450,NaN,1,Education,16,Y,650673,?,Cash loans,NaN,NaN,?,700k,NaN,₹5000,"1,20,000",Pensioner,High,Married,Owned,-11220,-13419,IT staff,2,2.0,Tuesday,12,Govt,0.8,0.7,0.3,NaN,0.34603598087973664,NaN,NaN,0.4645068696337057,ExtraValue,?,0.6020525900553526,NaN,0.3370550949739738,0.702980230963849,2021,?,?,error,,NaN,error,NaN,0.11811040559076358,NaN,NaN
1,CUST100001,69,male,Marrid,Salaried,50000,10000,12,Bad,0,2,Business,16,Y,272165,?,Cash loans,Y,Y,0,900000,₹200000,1000,"1,20,000",Workng,High,Separated,NaN,-12092,-12490,Drivr,3,NaN,NaN,12,Med,0.8,NaN,0.6,6101,error,1763,NaN,NaN,0.5594043846983144,,NaN,0.4000104955379503,NaN,Unknown,NaN,,823,,error,,error,?,NaN,NaN,NaN
2,CUST100002,46,other,Singl,Salaried,NaN,NaN,NaN,NaN,0,2,Shopping,11,YES,438093,?,RL,NaN,NaN,2,NaN,₹200000,7k,50000,Businessman,Secondary,NaN,Rent,-19822,-7838,IT staff,5,NaN,Wed,0,Business,0.8,0.9,NaN,6101,NaN,NaN,0.530113780541859,NaN,error,Unknown,Unknown,NaN,?,NaN,ExtraValue,NaN,0.47522270615276174,NaN,7978,0.20436277293007032,NaN,error,0.11811040559076358,NaN,NaN
3,CUST100003,32,NaN,Widowed,Unemployed,"1,20,000",₹200000,12 months,450,1,0,Personal,1,Yes,109000,1,Revolving loans,N,NO,0,900000,NaN,₹5000,50000,Pensioner,Incomplete Higher,Single,Owned,-13087,-11719,Laborer,2,1.0,Wed,12,Business,NaN,0.9,NaN,?,0.34603598087973664,ExtraValue,,,NaN,0.11269983119887728,NaN,,NaN,,NaN,NaN,?,NaN,error,NaN,0.12114014160842657,?,NaN,Unknown,?
4,CUST100004,60,female,Single,Self-Employed,200000,10000,48,NaN,3,?,Personal,2,Y,802383,?,CL,NaN,YES,?,NaN,₹200000,1000,50000,Working,Higher,Married,Owned,-24318,-545,Accountant,4,NaN,NaN,NaN,Govt,NaN,NaN,NaN,ExtraValue,ExtraValue,1763,,NaN,0.5594043846983144,6317,ExtraValue,NaN,NaN,NaN,2021,error,ExtraValue,Unknown,?,error,4665,ExtraValue,ExtraValue,Unknown,NaN

In [ ]:
dataset['gender'].value_counts()

gender
female    5284
male      5278
other     2541
Name: count, dtype: int64

In [ ]:
dataset['gender'] = dataset['gender'].fillna(dataset['gender'].mode()[0])

In [ ]:
dataset['marital_status'] = dataset['marital_status'].str.lower().str.strip()

In [ ]:
dataset['marital_status'].value_counts()

marital_status
singl       2417
widowed     2262
divorced    2255
marrid      2206
married     2170
single      2153
Name: count, dtype: int64

In [ ]:
dataset['marital_status'] = dataset['marital_status'].replace({
    'singl':'single',
    'marrid':'married'
})

In [ ]:
dataset['marital_status'].isnull().sum()

np.int64(2287)

In [ ]:
dataset['marital_status'] = dataset['marital_status'].fillna('unknown')

In [ ]:
dataset.head(5)

,customer_id,age,gender,marital_status,employment_type,annual_income,loan_amount,loan_term_months,credit_score,number_of_dependents,past_defaults,loan_purpose,current_residence_years,default,sk_id_curr,target,name_contract_type,flag_own_car,flag_own_realty,cnt_children,amt_income_total,amt_credit,amt_annuity,amt_goods_price,name_income_type,name_education_type,name_family_status,name_housing_type,days_birth,days_employed,occupation_type,cnt_fam_members,region_rating_client,weekday_appr_process_start,hour_appr_process_start,organization_type,ext_source_1,ext_source_2,ext_source_3,unwanted_column_1,unwanted_column_2,unwanted_column_3,unwanted_column_4,unwanted_column_5,unwanted_column_6,unwanted_column_7,unwanted_column_8,unwanted_column_9,unwanted_column_10,unwanted_column_11,unwanted_column_12,unwanted_column_13,unwanted_column_14,unwanted_column_15,unwanted_column_16,unwanted_column_17,unwanted_column_18,unwanted_column_19,unwanted_column_20,unwanted_column_21,unwanted_column_22
0,CUST100000,56,female,married,Unemployed,50000,10000,NaN,450,NaN,1,Education,16,Y,650673,?,Cash loans,NaN,NaN,?,700k,NaN,₹5000,"1,20,000",Pensioner,High,Married,Owned,-11220,-13419,IT staff,2,2.0,Tuesday,12,Govt,0.8,0.7,0.3,NaN,0.34603598087973664,NaN,NaN,0.4645068696337057,ExtraValue,?,0.6020525900553526,NaN,0.3370550949739738,0.702980230963849,2021,?,?,error,,NaN,error,NaN,0.11811040559076358,NaN,NaN
1,CUST100001,69,male,married,Salaried,50000,10000,12,Bad,0,2,Business,16,Y,272165,?,Cash loans,Y,Y,0,900000,₹200000,1000,"1,20,000",Workng,High,Separated,NaN,-12092,-12490,Drivr,3,NaN,NaN,12,Med,0.8,NaN,0.6,6101,error,1763,NaN,NaN,0.5594043846983144,,NaN,0.4000104955379503,NaN,Unknown,NaN,,823,,error,,error,?,NaN,NaN,NaN
2,CUST100002,46,other,single,Salaried,NaN,NaN,NaN,NaN,0,2,Shopping,11,YES,438093,?,RL,NaN,NaN,2,NaN,₹200000,7k,50000,Businessman,Secondary,NaN,Rent,-19822,-7838,IT staff,5,NaN,Wed,0,Business,0.8,0.9,NaN,6101,NaN,NaN,0.530113780541859,NaN,error,Unknown,Unknown,NaN,?,NaN,ExtraValue,NaN,0.47522270615276174,NaN,7978,0.20436277293007032,NaN,error,0.11811040559076358,NaN,NaN
3,CUST100003,32,female,widowed,Unemployed,"1,20,000",₹200000,12 months,450,1,0,Personal,1,Yes,109000,1,Revolving loans,N,NO,0,900000,NaN,₹5000,50000,Pensioner,Incomplete Higher,Single,Owned,-13087,-11719,Laborer,2,1.0,Wed,12,Business,NaN,0.9,NaN,?,0.34603598087973664,ExtraValue,,,NaN,0.11269983119887728,NaN,,NaN,,NaN,NaN,?,NaN,error,NaN,0.12114014160842657,?,NaN,Unknown,?
4,CUST100004,60,female,single,Self-Employed,200000,10000,48,NaN,3,?,Personal,2,Y,802383,?,CL,NaN,YES,?,NaN,₹200000,1000,50000,Working,Higher,Married,Owned,-24318,-545,Accountant,4,NaN,NaN,NaN,Govt,NaN,NaN,NaN,ExtraValue,ExtraValue,1763,,NaN,0.5594043846983144,6317,ExtraValue,NaN,NaN,NaN,2021,error,ExtraValue,Unknown,?,error,4665,ExtraValue,ExtraValue,Unknown,NaN

In [ ]:
dataset['employment_type'].value_counts()

employment_type
Self-Employed    2733
Retired          2696
Jobless          2547
Salaried         2545
Unemployed       2543
Name: count, dtype: int64

In [ ]:
dataset['employment_type'] = dataset['employment_type'].str.lower().str.strip()

In [ ]:
dataset['employment_type'].isna().sum()

np.int64(2686)

In [ ]:
dataset['employment_type'] = dataset['employment_type'].fillna(dataset['employment_type'].mode()[0])

In [ ]:
dataset['employment_type'].value_counts()

employment_type
self-employed    5419
retired          2696
jobless          2547
salaried         2545
unemployed       2543
Name: count, dtype: int64

In [ ]:
dataset.head(5)

,customer_id,age,gender,marital_status,employment_type,annual_income,loan_amount,loan_term_months,credit_score,number_of_dependents,past_defaults,loan_purpose,current_residence_years,default,sk_id_curr,target,name_contract_type,flag_own_car,flag_own_realty,cnt_children,amt_income_total,amt_credit,amt_annuity,amt_goods_price,name_income_type,name_education_type,name_family_status,name_housing_type,days_birth,days_employed,occupation_type,cnt_fam_members,region_rating_client,weekday_appr_process_start,hour_appr_process_start,organization_type,ext_source_1,ext_source_2,ext_source_3,unwanted_column_1,unwanted_column_2,unwanted_column_3,unwanted_column_4,unwanted_column_5,unwanted_column_6,unwanted_column_7,unwanted_column_8,unwanted_column_9,unwanted_column_10,unwanted_column_11,unwanted_column_12,unwanted_column_13,unwanted_column_14,unwanted_column_15,unwanted_column_16,unwanted_column_17,unwanted_column_18,unwanted_column_19,unwanted_column_20,unwanted_column_21,unwanted_column_22
0,CUST100000,56,female,married,unemployed,50000,10000,NaN,450,NaN,1,Education,16,Y,650673,?,Cash loans,NaN,NaN,?,700k,NaN,₹5000,"1,20,000",Pensioner,High,Married,Owned,-11220,-13419,IT staff,2,2.0,Tuesday,12,Govt,0.8,0.7,0.3,NaN,0.34603598087973664,NaN,NaN,0.4645068696337057,ExtraValue,?,0.6020525900553526,NaN,0.3370550949739738,0.702980230963849,2021,?,?,error,,NaN,error,NaN,0.11811040559076358,NaN,NaN
1,CUST100001,69,male,married,salaried,50000,10000,12,Bad,0,2,Business,16,Y,272165,?,Cash loans,Y,Y,0,900000,₹200000,1000,"1,20,000",Workng,High,Separated,NaN,-12092,-12490,Drivr,3,NaN,NaN,12,Med,0.8,NaN,0.6,6101,error,1763,NaN,NaN,0.5594043846983144,,NaN,0.4000104955379503,NaN,Unknown,NaN,,823,,error,,error,?,NaN,NaN,NaN
2,CUST100002,46,other,single,salaried,NaN,NaN,NaN,NaN,0,2,Shopping,11,YES,438093,?,RL,NaN,NaN,2,NaN,₹200000,7k,50000,Businessman,Secondary,NaN,Rent,-19822,-7838,IT staff,5,NaN,Wed,0,Business,0.8,0.9,NaN,6101,NaN,NaN,0.530113780541859,NaN,error,Unknown,Unknown,NaN,?,NaN,ExtraValue,NaN,0.47522270615276174,NaN,7978,0.20436277293007032,NaN,error,0.11811040559076358,NaN,NaN
3,CUST100003,32,female,widowed,unemployed,"1,20,000",₹200000,12 months,450,1,0,Personal,1,Yes,109000,1,Revolving loans,N,NO,0,900000,NaN,₹5000,50000,Pensioner,Incomplete Higher,Single,Owned,-13087,-11719,Laborer,2,1.0,Wed,12,Business,NaN,0.9,NaN,?,0.34603598087973664,ExtraValue,,,NaN,0.11269983119887728,NaN,,NaN,,NaN,NaN,?,NaN,error,NaN,0.12114014160842657,?,NaN,Unknown,?
4,CUST100004,60,female,single,self-employed,200000,10000,48,NaN,3,?,Personal,2,Y,802383,?,CL,NaN,YES,?,NaN,₹200000,1000,50000,Working,Higher,Married,Owned,-24318,-545,Accountant,4,NaN,NaN,NaN,Govt,NaN,NaN,NaN,ExtraValue,ExtraValue,1763,,NaN,0.5594043846983144,6317,ExtraValue,NaN,NaN,NaN,2021,error,ExtraValue,Unknown,?,error,4665,ExtraValue,ExtraValue,Unknown,NaN

In [ ]:
dataset['annual_income'].value_counts()

annual_income
1,20,000    2678
50000       2649
100k        2610
₹80000      2585
200000      2567
Name: count, dtype: int64

In [ ]:
import numpy as np

def clean_income(x):
    if pd.isna(x):
        return np.nan
    x = str(x).lower().replace(',', '').strip()

    # Handle 'k' or 'lakh' suffix
    if 'k' in x:
        return float(x.replace('k', '')) * 1000
    elif 'lakh' in x:
        return float(x.replace('lakh', '').strip()) * 100000
    else:
        try:
            return float(x)
        except:
            return np.nan

dataset['annual_income'] = dataset['annual_income'].apply(clean_income)

In [ ]:
dataset['annual_income'] = dataset['annual_income'].replace('[\$,]', '', regex=True).astype(float)

<>:1: SyntaxWarning: invalid escape sequence '\$'
<>:1: SyntaxWarning: invalid escape sequence '\$'
/tmp/ipython-input-1452909548.py:1: SyntaxWarning: invalid escape sequence '\$'
  dataset['annual_income'] = dataset['annual_income'].replace('[\$,]', '', regex=True).astype(float)

In [ ]:
dataset['annual_income'].describe()

count     10504.000000
mean     116927.837014
std       53758.801073
min       50000.000000
25%       50000.000000
50%      100000.000000
75%      120000.000000
max      200000.000000
Name: annual_income, dtype: float64

In [ ]:
dataset['annual_income'] = dataset['annual_income'].fillna(dataset['annual_income'].median())

In [ ]:
dataset['annual_income'].isna().sum()

np.int64(0)

In [ ]:
dataset['annual_income'] = dataset['annual_income'].astype(int)

In [ ]:
dataset['annual_income'].shape

(15750,)

In [ ]:
dataset.head(5)

,customer_id,age,gender,marital_status,employment_type,annual_income,loan_amount,loan_term_months,credit_score,number_of_dependents,past_defaults,loan_purpose,current_residence_years,default,sk_id_curr,target,name_contract_type,flag_own_car,flag_own_realty,cnt_children,amt_income_total,amt_credit,amt_annuity,amt_goods_price,name_income_type,name_education_type,name_family_status,name_housing_type,days_birth,days_employed,occupation_type,cnt_fam_members,region_rating_client,weekday_appr_process_start,hour_appr_process_start,organization_type,ext_source_1,ext_source_2,ext_source_3,unwanted_column_1,unwanted_column_2,unwanted_column_3,unwanted_column_4,unwanted_column_5,unwanted_column_6,unwanted_column_7,unwanted_column_8,unwanted_column_9,unwanted_column_10,unwanted_column_11,unwanted_column_12,unwanted_column_13,unwanted_column_14,unwanted_column_15,unwanted_column_16,unwanted_column_17,unwanted_column_18,unwanted_column_19,unwanted_column_20,unwanted_column_21,unwanted_column_22
0,CUST100000,56,female,married,unemployed,50000,10000,NaN,450,NaN,1,Education,16,Y,650673,?,Cash loans,NaN,NaN,?,700k,NaN,₹5000,"1,20,000",Pensioner,High,Married,Owned,-11220,-13419,IT staff,2,2.0,Tuesday,12,Govt,0.8,0.7,0.3,NaN,0.34603598087973664,NaN,NaN,0.4645068696337057,ExtraValue,?,0.6020525900553526,NaN,0.3370550949739738,0.702980230963849,2021,?,?,error,,NaN,error,NaN,0.11811040559076358,NaN,NaN
1,CUST100001,69,male,married,salaried,50000,10000,12,Bad,0,2,Business,16,Y,272165,?,Cash loans,Y,Y,0,900000,₹200000,1000,"1,20,000",Workng,High,Separated,NaN,-12092,-12490,Drivr,3,NaN,NaN,12,Med,0.8,NaN,0.6,6101,error,1763,NaN,NaN,0.5594043846983144,,NaN,0.4000104955379503,NaN,Unknown,NaN,,823,,error,,error,?,NaN,NaN,NaN
2,CUST100002,46,other,single,salaried,100000,NaN,NaN,NaN,0,2,Shopping,11,YES,438093,?,RL,NaN,NaN,2,NaN,₹200000,7k,50000,Businessman,Secondary,NaN,Rent,-19822,-7838,IT staff,5,NaN,Wed,0,Business,0.8,0.9,NaN,6101,NaN,NaN,0.530113780541859,NaN,error,Unknown,Unknown,NaN,?,NaN,ExtraValue,NaN,0.47522270615276174,NaN,7978,0.20436277293007032,NaN,error,0.11811040559076358,NaN,NaN
3,CUST100003,32,female,widowed,unemployed,120000,₹200000,12 months,450,1,0,Personal,1,Yes,109000,1,Revolving loans,N,NO,0,900000,NaN,₹5000,50000,Pensioner,Incomplete Higher,Single,Owned,-13087,-11719,Laborer,2,1.0,Wed,12,Business,NaN,0.9,NaN,?,0.34603598087973664,ExtraValue,,,NaN,0.11269983119887728,NaN,,NaN,,NaN,NaN,?,NaN,error,NaN,0.12114014160842657,?,NaN,Unknown,?
4,CUST100004,60,female,single,self-employed,200000,10000,48,NaN,3,?,Personal,2,Y,802383,?,CL,NaN,YES,?,NaN,₹200000,1000,50000,Working,Higher,Married,Owned,-24318,-545,Accountant,4,NaN,NaN,NaN,Govt,NaN,NaN,NaN,ExtraValue,ExtraValue,1763,,NaN,0.5594043846983144,6317,ExtraValue,NaN,NaN,NaN,2021,error,ExtraValue,Unknown,?,error,4665,ExtraValue,ExtraValue,Unknown,NaN

In [ ]:
dataset['loan_amount'].isna().sum()

np.int64(3108)

In [ ]:
dataset['loan_amount'].value_counts()

loan_amount
150000     3194
10000      3170
₹200000    3152
300k       3126
Name: count, dtype: int64

In [ ]:
import numpy as np
import pandas as pd

def clean_loan_amount(x):
    if pd.isna(x):
        return np.nan

    # convert to lowercase string and remove symbols/spaces
    x = str(x).lower().replace(',', '').replace('₹', '').replace('$', '').strip()

    # handle k/lakh suffixes
    if 'k' in x:
        num = x.replace('k', '').strip()
        return float(num) * 1000 if num.replace('.', '', 1).isdigit() else np.nan
    elif 'lakh' in x:
        num = x.replace('lakh', '').strip()
        return float(num) * 100000 if num.replace('.', '', 1).isdigit() else np.nan

    # handle plain numeric strings
    if x.replace('.', '', 1).isdigit():
        return float(x)

    # invalid or text-like entries
    return np.nan


# Apply cleaning function
dataset['loan_amount'] = dataset['loan_amount'].apply(clean_loan_amount)

# Optional: Fill missing values with median for project simplicity
dataset['loan_amount'] = dataset['loan_amount'].fillna(dataset['loan_amount'].median())

In [ ]:
dataset['loan_amount'].isna().sum()

np.int64(0)

In [ ]:
dataset['loan_amount'] = dataset['loan_amount'].astype(int)

In [ ]:
dataset.head(5)

,customer_id,age,gender,marital_status,employment_type,annual_income,loan_amount,loan_term_months,credit_score,number_of_dependents,past_defaults,loan_purpose,current_residence_years,default,sk_id_curr,target,name_contract_type,flag_own_car,flag_own_realty,cnt_children,amt_income_total,amt_credit,amt_annuity,amt_goods_price,name_income_type,name_education_type,name_family_status,name_housing_type,days_birth,days_employed,occupation_type,cnt_fam_members,region_rating_client,weekday_appr_process_start,hour_appr_process_start,organization_type,ext_source_1,ext_source_2,ext_source_3,unwanted_column_1,unwanted_column_2,unwanted_column_3,unwanted_column_4,unwanted_column_5,unwanted_column_6,unwanted_column_7,unwanted_column_8,unwanted_column_9,unwanted_column_10,unwanted_column_11,unwanted_column_12,unwanted_column_13,unwanted_column_14,unwanted_column_15,unwanted_column_16,unwanted_column_17,unwanted_column_18,unwanted_column_19,unwanted_column_20,unwanted_column_21,unwanted_column_22
0,CUST100000,56,female,married,unemployed,50000,10000,NaN,450,NaN,1,Education,16,Y,650673,?,Cash loans,NaN,NaN,?,700k,NaN,₹5000,"1,20,000",Pensioner,High,Married,Owned,-11220,-13419,IT staff,2,2.0,Tuesday,12,Govt,0.8,0.7,0.3,NaN,0.34603598087973664,NaN,NaN,0.4645068696337057,ExtraValue,?,0.6020525900553526,NaN,0.3370550949739738,0.702980230963849,2021,?,?,error,,NaN,error,NaN,0.11811040559076358,NaN,NaN
1,CUST100001,69,male,married,salaried,50000,10000,12,Bad,0,2,Business,16,Y,272165,?,Cash loans,Y,Y,0,900000,₹200000,1000,"1,20,000",Workng,High,Separated,NaN,-12092,-12490,Drivr,3,NaN,NaN,12,Med,0.8,NaN,0.6,6101,error,1763,NaN,NaN,0.5594043846983144,,NaN,0.4000104955379503,NaN,Unknown,NaN,,823,,error,,error,?,NaN,NaN,NaN
2,CUST100002,46,other,single,salaried,100000,150000,NaN,NaN,0,2,Shopping,11,YES,438093,?,RL,NaN,NaN,2,NaN,₹200000,7k,50000,Businessman,Secondary,NaN,Rent,-19822,-7838,IT staff,5,NaN,Wed,0,Business,0.8,0.9,NaN,6101,NaN,NaN,0.530113780541859,NaN,error,Unknown,Unknown,NaN,?,NaN,ExtraValue,NaN,0.47522270615276174,NaN,7978,0.20436277293007032,NaN,error,0.11811040559076358,NaN,NaN
3,CUST100003,32,female,widowed,unemployed,120000,200000,12 months,450,1,0,Personal,1,Yes,109000,1,Revolving loans,N,NO,0,900000,NaN,₹5000,50000,Pensioner,Incomplete Higher,Single,Owned,-13087,-11719,Laborer,2,1.0,Wed,12,Business,NaN,0.9,NaN,?,0.34603598087973664,ExtraValue,,,NaN,0.11269983119887728,NaN,,NaN,,NaN,NaN,?,NaN,error,NaN,0.12114014160842657,?,NaN,Unknown,?
4,CUST100004,60,female,single,self-employed,200000,10000,48,NaN,3,?,Personal,2,Y,802383,?,CL,NaN,YES,?,NaN,₹200000,1000,50000,Working,Higher,Married,Owned,-24318,-545,Accountant,4,NaN,NaN,NaN,Govt,NaN,NaN,NaN,ExtraValue,ExtraValue,1763,,NaN,0.5594043846983144,6317,ExtraValue,NaN,NaN,NaN,2021,error,ExtraValue,Unknown,?,error,4665,ExtraValue,ExtraValue,Unknown,NaN

In [ ]:
dataset.columns

Index(['customer_id', 'age', 'gender', 'marital_status', 'employment_type',
       'annual_income', 'loan_amount', 'loan_term_months', 'credit_score',
       'number_of_dependents', 'past_defaults', 'loan_purpose',
       'current_residence_years', 'default', 'sk_id_curr', 'target',
       'name_contract_type', 'flag_own_car', 'flag_own_realty', 'cnt_children',
       'amt_income_total', 'amt_credit', 'amt_annuity', 'amt_goods_price',
       'name_income_type', 'name_education_type', 'name_family_status',
       'name_housing_type', 'days_birth', 'days_employed', 'occupation_type',
       'cnt_fam_members', 'region_rating_client', 'weekday_appr_process_start',
       'hour_appr_process_start', 'organization_type', 'ext_source_1',
       'ext_source_2', 'ext_source_3', 'unwanted_column_1',
       'unwanted_column_2', 'unwanted_column_3', 'unwanted_column_4',
       'unwanted_column_5', 'unwanted_column_6', 'unwanted_column_7',
       'unwanted_column_8', 'unwanted_column_9', 'unwanted_column_10',
       'unwanted_column_11', 'unwanted_column_12', 'unwanted_column_13',
       'unwanted_column_14', 'unwanted_column_15', 'unwanted_column_16',
       'unwanted_column_17', 'unwanted_column_18', 'unwanted_column_19',
       'unwanted_column_20', 'unwanted_column_21', 'unwanted_column_22'],
      dtype='object')

In [ ]:
# Columns to drop
drop_cols = [
    'unwanted_column_1', 'unwanted_column_2', 'unwanted_column_3',
    'unwanted_column_4', 'unwanted_column_5', 'unwanted_column_6',
    'unwanted_column_7', 'unwanted_column_8', 'unwanted_column_9',
    'unwanted_column_10', 'unwanted_column_11', 'unwanted_column_12',
    'unwanted_column_13', 'unwanted_column_14', 'unwanted_column_15',
    'unwanted_column_16', 'unwanted_column_17', 'unwanted_column_18',
    'unwanted_column_19', 'unwanted_column_20', 'unwanted_column_21',
    'unwanted_column_22'

]

# Drop them safely (ignore errors if some columns are missing)
dataset.drop(columns=drop_cols, inplace=True, errors='ignore')

# Check remaining columns
print("Remaining columns:\n", dataset.columns.tolist())

Remaining columns:
 ['customer_id', 'age', 'gender', 'marital_status', 'employment_type', 'annual_income', 'loan_amount', 'loan_term_months', 'credit_score', 'number_of_dependents', 'past_defaults', 'loan_purpose', 'current_residence_years', 'default', 'sk_id_curr', 'target', 'name_contract_type', 'flag_own_car', 'flag_own_realty', 'cnt_children', 'amt_income_total', 'amt_credit', 'amt_annuity', 'amt_goods_price', 'name_income_type', 'name_education_type', 'name_family_status', 'name_housing_type', 'days_birth', 'days_employed', 'occupation_type', 'cnt_fam_members', 'region_rating_client', 'weekday_appr_process_start', 'hour_appr_process_start', 'organization_type', 'ext_source_1', 'ext_source_2', 'ext_source_3']

In [ ]:
dataset.head(5)

,customer_id,age,gender,marital_status,employment_type,annual_income,loan_amount,loan_term_months,credit_score,number_of_dependents,past_defaults,loan_purpose,current_residence_years,default,sk_id_curr,target,name_contract_type,flag_own_car,flag_own_realty,cnt_children,amt_income_total,amt_credit,amt_annuity,amt_goods_price,name_income_type,name_education_type,name_family_status,name_housing_type,days_birth,days_employed,occupation_type,cnt_fam_members,region_rating_client,weekday_appr_process_start,hour_appr_process_start,organization_type,ext_source_1,ext_source_2,ext_source_3
0,CUST100000,56,female,married,unemployed,50000,10000,NaN,450,NaN,1,Education,16,Y,650673,?,Cash loans,NaN,NaN,?,700k,NaN,₹5000,"1,20,000",Pensioner,High,Married,Owned,-11220,-13419,IT staff,2,2.0,Tuesday,12,Govt,0.8,0.7,0.3
1,CUST100001,69,male,married,salaried,50000,10000,12,Bad,0,2,Business,16,Y,272165,?,Cash loans,Y,Y,0,900000,₹200000,1000,"1,20,000",Workng,High,Separated,NaN,-12092,-12490,Drivr,3,NaN,NaN,12,Med,0.8,NaN,0.6
2,CUST100002,46,other,single,salaried,100000,150000,NaN,NaN,0,2,Shopping,11,YES,438093,?,RL,NaN,NaN,2,NaN,₹200000,7k,50000,Businessman,Secondary,NaN,Rent,-19822,-7838,IT staff,5,NaN,Wed,0,Business,0.8,0.9,NaN
3,CUST100003,32,female,widowed,unemployed,120000,200000,12 months,450,1,0,Personal,1,Yes,109000,1,Revolving loans,N,NO,0,900000,NaN,₹5000,50000,Pensioner,Incomplete Higher,Single,Owned,-13087,-11719,Laborer,2,1.0,Wed,12,Business,NaN,0.9,NaN
4,CUST100004,60,female,single,self-employed,200000,10000,48,NaN,3,?,Personal,2,Y,802383,?,CL,NaN,YES,?,NaN,₹200000,1000,50000,Working,Higher,Married,Owned,-24318,-545,Accountant,4,NaN,NaN,NaN,Govt,NaN,NaN,NaN

In [ ]:
dataset['age'].value_counts()

age
 43     636
 34     322
-5      320
 30     314
 40     313
 62     312
 45     310
 46     309
 64     305
 32     303
 66     302
 41     300
 54     300
 42     298
 35     297
 59     296
 56     295
 50     293
 29     292
 36     292
 33     292
 61     291
 39     291
 20     290
 19     290
 38     289
 21     289
 68     288
 25     287
 27     286
 52     286
 49     282
 69     282
 26     276
 28     276
 23     275
 51     274
 37     273
 18     272
 58     272
 22     272
 53     270
 55     269
 65     269
 150    267
 47     267
 57     266
 24     265
 31     263
 60     261
 48     261
 67     261
 63     249
 44     240
Name: count, dtype: int64

In [ ]:
dataset['age'] = dataset['age'].apply(
    lambda x: 25 if x < 18 else (32 if x > 100 else x)
)

In [ ]:
dataset['gender'].value_counts()

gender
female    7931
male      5278
other     2541
Name: count, dtype: int64

In [ ]:
dataset['loan_term_months'].dtype

dtype('O')

In [ ]:
dataset['loan_term_months'].value_counts()

loan_term_months
24           2310
60           2300
12           2261
12 months    2241
48           2222
36           2221
Name: count, dtype: int64

In [ ]:
dataset['loan_term_months'] = dataset['loan_term_months'].astype(str).str.replace('months', '', case=False).str.strip()
dataset['loan_term_months'] = pd.to_numeric(dataset['loan_term_months'], errors='coerce')

In [ ]:
median_term = dataset['loan_term_months'].median()
dataset['loan_term_months'].fillna(median_term, inplace=True)

/tmp/ipython-input-3573966888.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['loan_term_months'].fillna(median_term, inplace=True)

In [ ]:
dataset['loan_term_months'].value_counts()

loan_term_months
24.0    4505
12.0    4502
60.0    2300
48.0    2222
36.0    2221
Name: count, dtype: int64

In [ ]:
dataset.head(5)

,customer_id,age,gender,marital_status,employment_type,annual_income,loan_amount,loan_term_months,credit_score,number_of_dependents,past_defaults,loan_purpose,current_residence_years,default,sk_id_curr,target,name_contract_type,flag_own_car,flag_own_realty,cnt_children,amt_income_total,amt_credit,amt_annuity,amt_goods_price,name_income_type,name_education_type,name_family_status,name_housing_type,days_birth,days_employed,occupation_type,cnt_fam_members,region_rating_client,weekday_appr_process_start,hour_appr_process_start,organization_type,ext_source_1,ext_source_2,ext_source_3
0,CUST100000,56,female,married,unemployed,50000,10000,24.0,450,NaN,1,Education,16,Y,650673,?,Cash loans,NaN,NaN,?,700k,NaN,₹5000,"1,20,000",Pensioner,High,Married,Owned,-11220,-13419,IT staff,2,2.0,Tuesday,12,Govt,0.8,0.7,0.3
1,CUST100001,69,male,married,salaried,50000,10000,12.0,Bad,0,2,Business,16,Y,272165,?,Cash loans,Y,Y,0,900000,₹200000,1000,"1,20,000",Workng,High,Separated,NaN,-12092,-12490,Drivr,3,NaN,NaN,12,Med,0.8,NaN,0.6
2,CUST100002,46,other,single,salaried,100000,150000,24.0,NaN,0,2,Shopping,11,YES,438093,?,RL,NaN,NaN,2,NaN,₹200000,7k,50000,Businessman,Secondary,NaN,Rent,-19822,-7838,IT staff,5,NaN,Wed,0,Business,0.8,0.9,NaN
3,CUST100003,32,female,widowed,unemployed,120000,200000,12.0,450,1,0,Personal,1,Yes,109000,1,Revolving loans,N,NO,0,900000,NaN,₹5000,50000,Pensioner,Incomplete Higher,Single,Owned,-13087,-11719,Laborer,2,1.0,Wed,12,Business,NaN,0.9,NaN
4,CUST100004,60,female,single,self-employed,200000,10000,48.0,NaN,3,?,Personal,2,Y,802383,?,CL,NaN,YES,?,NaN,₹200000,1000,50000,Working,Higher,Married,Owned,-24318,-545,Accountant,4,NaN,NaN,NaN,Govt,NaN,NaN,NaN

In [ ]:
dataset['credit_score'].isna().sum()

np.int64(2641)

In [ ]:
dataset['credit_score'] = pd.to_numeric(dataset['credit_score'], errors='coerce')
dataset['credit_score'].fillna(dataset['credit_score'].median(), inplace=True)
dataset['credit_score'] = dataset['credit_score'].astype(int)

/tmp/ipython-input-3435825841.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['credit_score'].fillna(dataset['credit_score'].median(), inplace=True)

In [ ]:
dataset['credit_score'].value_counts()

credit_score
450    7907
300    2698
700    2597
900    2548
Name: count, dtype: int64

In [ ]:
dataset['credit_score'].isna().sum()

np.int64(0)

In [ ]:
dataset['number_of_dependents'].value_counts()

number_of_dependents
4          2295
2          2259
1          2255
Unknown    2244
3          2243
0          2160
Name: count, dtype: int64

In [ ]:
dataset['number_of_dependents'] = pd.to_numeric(dataset['number_of_dependents'], errors='coerce')
dataset.loc[dataset['number_of_dependents'] < 0, 'number_of_dependents'] = np.nan
dataset['number_of_dependents'].fillna(dataset['number_of_dependents'].median(), inplace=True)
dataset['number_of_dependents'] = dataset['number_of_dependents'].astype(int)

/tmp/ipython-input-3121816883.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['number_of_dependents'].fillna(dataset['number_of_dependents'].median(), inplace=True)

In [ ]:
dataset['past_defaults'] = pd.to_numeric(dataset['past_defaults'], errors='coerce').fillna(0).astype(int)

In [ ]:
dataset.head(5)

,customer_id,age,gender,marital_status,employment_type,annual_income,loan_amount,loan_term_months,credit_score,number_of_dependents,past_defaults,loan_purpose,current_residence_years,default,sk_id_curr,target,name_contract_type,flag_own_car,flag_own_realty,cnt_children,amt_income_total,amt_credit,amt_annuity,amt_goods_price,name_income_type,name_education_type,name_family_status,name_housing_type,days_birth,days_employed,occupation_type,cnt_fam_members,region_rating_client,weekday_appr_process_start,hour_appr_process_start,organization_type,ext_source_1,ext_source_2,ext_source_3
0,CUST100000,56,female,married,unemployed,50000,10000,24.0,450,2,1,Education,16,Y,650673,?,Cash loans,NaN,NaN,?,700k,NaN,₹5000,"1,20,000",Pensioner,High,Married,Owned,-11220,-13419,IT staff,2,2.0,Tuesday,12,Govt,0.8,0.7,0.3
1,CUST100001,69,male,married,salaried,50000,10000,12.0,450,0,2,Business,16,Y,272165,?,Cash loans,Y,Y,0,900000,₹200000,1000,"1,20,000",Workng,High,Separated,NaN,-12092,-12490,Drivr,3,NaN,NaN,12,Med,0.8,NaN,0.6
2,CUST100002,46,other,single,salaried,100000,150000,24.0,450,0,2,Shopping,11,YES,438093,?,RL,NaN,NaN,2,NaN,₹200000,7k,50000,Businessman,Secondary,NaN,Rent,-19822,-7838,IT staff,5,NaN,Wed,0,Business,0.8,0.9,NaN
3,CUST100003,32,female,widowed,unemployed,120000,200000,12.0,450,1,0,Personal,1,Yes,109000,1,Revolving loans,N,NO,0,900000,NaN,₹5000,50000,Pensioner,Incomplete Higher,Single,Owned,-13087,-11719,Laborer,2,1.0,Wed,12,Business,NaN,0.9,NaN
4,CUST100004,60,female,single,self-employed,200000,10000,48.0,450,3,0,Personal,2,Y,802383,?,CL,NaN,YES,?,NaN,₹200000,1000,50000,Working,Higher,Married,Owned,-24318,-545,Accountant,4,NaN,NaN,NaN,Govt,NaN,NaN,NaN

In [ ]:
dataset['loan_purpose'].value_counts()

loan_purpose
Home         2368
Education    2256
Car          2231
Business     2226
Shopping     2215
Personal     2202
Name: count, dtype: int64

In [ ]:
dataset['loan_purpose'].fillna(dataset['loan_purpose'].mode()[0], inplace=True)

/tmp/ipython-input-753519944.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['loan_purpose'].fillna(dataset['loan_purpose'].mode()[0], inplace=True)

In [ ]:
dataset['default'].value_counts()

default
Yes    2297
No     2295
YES    2280
N      2276
Y      2245
NO     2137
Name: count, dtype: int64

In [ ]:
dataset['default'].isna().sum()

np.int64(2220)

In [ ]:
dataset['default'] = dataset['default'].astype(str).str.lower().str.strip()
dataset['default'] = dataset['default'].replace({'y': 'yes', 'n': 'no', 'no': 'no'})

In [ ]:
dataset['default'].unique()

array(['yes', 'no', 'nan'], dtype=object)

In [ ]:
dataset['default'].unique()

array(['yes', 'no', 'nan'], dtype=object)

In [ ]:
dataset['default'] = dataset['default'].replace({'yes': 1, 'no': 0})

In [ ]:
dataset['default'] = pd.to_numeric(dataset['default'], errors='coerce')

In [ ]:
dataset['default'] = dataset['default'].fillna(0).astype(int)

In [ ]:
dataset['default'].value_counts()

default
0    8928
1    6822
Name: count, dtype: int64

In [ ]:
dataset.drop(['sk_id_curr', 'target'], axis=1, inplace=True)

In [ ]:
dataset['name_contract_type'].value_counts()

name_contract_type
CL                 3990
Revolving loans    3931
RL                 3916
Cash loans         3913
Name: count, dtype: int64

In [ ]:
dataset['name_contract_type'] = dataset['name_contract_type'].str.lower().replace({'cl': 'cash loan', 'rl': 'revolving loan'})

In [ ]:
dataset['name_contract_type'] = dataset['name_contract_type'].str.lower().replace({'cash loans': 'cash loan', 'revolving loans': 'revolving loan'})

In [ ]:
dataset['name_contract_type'].isna().sum()

np.int64(0)

In [ ]:
dataset['flag_own_car'].value_counts()

flag_own_car
N      3262
NO     3148
YES    3100
Y      3084
Name: count, dtype: int64

In [ ]:
dataset['flag_own_car'] = dataset['flag_own_car'].astype(str).str.lower().str.strip()
dataset['flag_own_car'] = dataset['flag_own_car'].replace({'y': 1, 'yes': 1, 'n': 0, 'no': 0, 'nan': np.nan})
dataset['flag_own_car'].fillna(0, inplace=True)
dataset['flag_own_car'] = dataset['flag_own_car'].astype(int)

/tmp/ipython-input-3989121408.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset['flag_own_car'] = dataset['flag_own_car'].replace({'y': 1, 'yes': 1, 'n': 0, 'no': 0, 'nan': np.nan})
/tmp/ipython-input-3989121408.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['flag_own_car'].fillna(0, inplace=True)

In [ ]:
dataset['flag_own_realty'] = dataset['flag_own_realty'].astype(str).str.lower().str.strip()
dataset['flag_own_realty'] = dataset['flag_own_realty'].replace({'y': 1, 'yes': 1, 'n': 0, 'no': 0, 'nan': np.nan})
dataset['flag_own_realty'].fillna(0, inplace=True)
dataset['flag_own_realty'] = dataset['flag_own_realty'].astype(int)

/tmp/ipython-input-2180259029.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset['flag_own_realty'] = dataset['flag_own_realty'].replace({'y': 1, 'yes': 1, 'n': 0, 'no': 0, 'nan': np.nan})
/tmp/ipython-input-2180259029.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['flag_own_realty'].fillna(0, inplace=True)

In [ ]:
dataset['flag_own_realty'].value_counts()

flag_own_realty
0    9449
1    6301
Name: count, dtype: int64

In [ ]:
dataset.drop(['cnt_children'], axis=1, inplace=True)

In [ ]:
dataset.drop(['amt_income_total'], axis=1, inplace=True)

In [ ]:
dataset.drop('loan_amount', axis=1, inplace=True)

In [ ]:
dataset['amt_credit'].value_counts()

amt_credit
300000     3192
₹200000    3168
500k       3162
1000000    3159
Name: count, dtype: int64

In [ ]:
dataset['amt_credit'] = dataset['amt_credit'].astype(str).str.replace('[₹,]', '', regex=True).str.strip()
dataset['amt_credit'] = pd.to_numeric(dataset['amt_credit'], errors='coerce')
dataset['amt_credit'].fillna(dataset['amt_credit'].median(), inplace=True)

/tmp/ipython-input-1715016252.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['amt_credit'].fillna(dataset['amt_credit'].median(), inplace=True)

In [ ]:
def clean_credit(x):
    if pd.isna(x):
        return np.nan
    x = str(x).lower().replace('₹', '').replace(',', '').strip()
    if 'k' in x:
        return float(x.replace('k', '')) * 1000
    try:
        return float(x)
    except:
        return np.nan

dataset['amt_credit'] = dataset['amt_credit'].apply(clean_credit)
dataset['amt_credit'].fillna(dataset['amt_credit'].median(), inplace=True)

/tmp/ipython-input-107663778.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['amt_credit'].fillna(dataset['amt_credit'].median(), inplace=True)

In [ ]:
dataset['amt_credit'].value_counts()

amt_credit
300000.0     9423
200000.0     3168
1000000.0    3159
Name: count, dtype: int64

In [ ]:
import pandas as pd

# Step 1: Define a cleaning function
def clean_amount(value):
    if pd.isna(value):
        return None
    value = str(value).strip().lower().replace('₹', '').replace(',', '').replace(' ', '')

    # Handle shorthand like 5k or 2.5m
    if 'k' in value:
        try:
            return float(value.replace('k', '')) * 1000
        except:
            return None
    elif 'm' in value:
        try:
            return float(value.replace('m', '')) * 1_000_000
        except:
            return None
    else:
        try:
            return float(value)
        except:
            return None

# Step 2: Apply to your column
dataset['amt_annuity'] = dataset['amt_annuity'].apply(clean_amount)

# Step 3: Fill missing values (optional — median is a safe choice)
dataset['amt_annuity'] = dataset['amt_annuity'].fillna(dataset['amt_annuity'].median())

In [ ]:
dataset['amt_annuity'] = dataset['amt_annuity'].astype(int)

In [ ]:
dataset['amt_annuity'].value_counts()

amt_annuity
5000    6298
1000    3173
6000    3167
7000    3112
Name: count, dtype: int64

In [ ]:
# Step 1: Keep a backup before modifying
dataset['amt_annuity_backup'] = dataset['amt_annuity']

# Step 2: Convert all values to string
dataset['amt_annuity'] = dataset['amt_annuity'].astype(str)

# Step 3: Clean and normalize values safely
dataset['amt_annuity'] = (
    dataset['amt_annuity']
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.replace('k', '000', regex=False)
    .astype(float)
)

# Step 4: Verify
dataset['amt_annuity'].value_counts()

amt_annuity
5000.0    6298
1000.0    3173
6000.0    3167
7000.0    3112
Name: count, dtype: int64

In [ ]:
cols = list(dataset.columns)
cols.remove('amt_credit')
cols.remove('amt_annuity')

cols.insert(6, 'amt_credit')
cols.insert(7, 'amt_annuity')

dataset = dataset[cols]

In [ ]:
dataset['amt_credit'] = dataset['amt_credit'].astype(int)

In [ ]:
dataset.drop('amt_goods_price', axis=1, inplace=True)

In [ ]:
dataset.head(5)

,customer_id,age,gender,marital_status,employment_type,annual_income,amt_credit,amt_annuity,loan_term_months,credit_score,number_of_dependents,past_defaults,loan_purpose,current_residence_years,default,name_contract_type,flag_own_car,flag_own_realty,name_income_type,name_education_type,name_family_status,name_housing_type,days_birth,days_employed,occupation_type,cnt_fam_members,region_rating_client,weekday_appr_process_start,hour_appr_process_start,organization_type,ext_source_1,ext_source_2,ext_source_3,amt_annuity_backup
0,CUST100000,56,female,married,unemployed,50000,300000,5000.0,24.0,450,2,1,Education,16,1,cash loan,0,0,Pensioner,High,Married,Owned,-11220,-13419,IT staff,2,2.0,Tuesday,12,Govt,0.8,0.7,0.3,5000
1,CUST100001,69,male,married,salaried,50000,200000,1000.0,12.0,450,0,2,Business,16,1,cash loan,1,1,Workng,High,Separated,NaN,-12092,-12490,Drivr,3,NaN,NaN,12,Med,0.8,NaN,0.6,1000
2,CUST100002,46,other,single,salaried,100000,200000,7000.0,24.0,450,0,2,Shopping,11,1,revolving loan,0,0,Businessman,Secondary,NaN,Rent,-19822,-7838,IT staff,5,NaN,Wed,0,Business,0.8,0.9,NaN,7000
3,CUST100003,32,female,widowed,unemployed,120000,300000,5000.0,12.0,450,1,0,Personal,1,1,revolving loan,0,0,Pensioner,Incomplete Higher,Single,Owned,-13087,-11719,Laborer,2,1.0,Wed,12,Business,NaN,0.9,NaN,5000
4,CUST100004,60,female,single,self-employed,200000,200000,1000.0,48.0,450,3,0,Personal,2,1,cash loan,0,1,Working,Higher,Married,Owned,-24318,-545,Accountant,4,NaN,NaN,NaN,Govt,NaN,NaN,NaN,1000

In [ ]:
dataset['name_income_type'].value_counts()

name_income_type
Working        2669
Student        2639
Pensioner      2617
Workng         2605
Businessman    2595
Name: count, dtype: int64

In [ ]:
dataset['name_income_type'] = dataset['name_income_type'].str.lower().replace({'workng':'working'})

In [ ]:
dataset['name_income_type'].fillna(dataset['name_income_type'].mode()[0], inplace=True)

/tmp/ipython-input-2645880089.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['name_income_type'].fillna(dataset['name_income_type'].mode()[0], inplace=True)

In [ ]:
dataset.head(5)

,customer_id,age,gender,marital_status,employment_type,annual_income,amt_credit,amt_annuity,loan_term_months,credit_score,number_of_dependents,past_defaults,loan_purpose,current_residence_years,default,name_contract_type,flag_own_car,flag_own_realty,name_income_type,name_education_type,name_family_status,name_housing_type,days_birth,days_employed,occupation_type,cnt_fam_members,region_rating_client,weekday_appr_process_start,hour_appr_process_start,organization_type,ext_source_1,ext_source_2,ext_source_3,amt_annuity_backup
0,CUST100000,56,female,married,unemployed,50000,300000,5000.0,24.0,450,2,1,Education,16,1,cash loan,0,0,pensioner,High,Married,Owned,-11220,-13419,IT staff,2,2.0,Tuesday,12,Govt,0.8,0.7,0.3,5000
1,CUST100001,69,male,married,salaried,50000,200000,1000.0,12.0,450,0,2,Business,16,1,cash loan,1,1,working,High,Separated,NaN,-12092,-12490,Drivr,3,NaN,NaN,12,Med,0.8,NaN,0.6,1000
2,CUST100002,46,other,single,salaried,100000,200000,7000.0,24.0,450,0,2,Shopping,11,1,revolving loan,0,0,businessman,Secondary,NaN,Rent,-19822,-7838,IT staff,5,NaN,Wed,0,Business,0.8,0.9,NaN,7000
3,CUST100003,32,female,widowed,unemployed,120000,300000,5000.0,12.0,450,1,0,Personal,1,1,revolving loan,0,0,pensioner,Incomplete Higher,Single,Owned,-13087,-11719,Laborer,2,1.0,Wed,12,Business,NaN,0.9,NaN,5000
4,CUST100004,60,female,single,self-employed,200000,200000,1000.0,48.0,450,3,0,Personal,2,1,cash loan,0,1,working,Higher,Married,Owned,-24318,-545,Accountant,4,NaN,NaN,NaN,Govt,NaN,NaN,NaN,1000

In [ ]:
dataset['name_education_type'] = dataset['name_education_type'].str.lower().str.strip()
dataset['name_education_type'].replace({
    'high': 'secondary',
    'incomplete higher': 'higher'
}, inplace=True)
dataset['name_education_type'].fillna(dataset['name_education_type'].mode()[0], inplace=True)

/tmp/ipython-input-4164629113.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['name_education_type'].replace({

In [ ]:
dataset['name_education_type'].value_counts()

name_education_type
higher             7871
secondary          5235
academic degree    2644
Name: count, dtype: int64

In [ ]:
dataset['name_family_status'] = dataset['name_family_status'].str.lower()

In [ ]:
import numpy as np

# Create mask for missing values
mask = dataset['name_family_status'].isna()

# Randomly select existing values (uniform distribution)
random_choices = np.random.choice(
    dataset['name_family_status'].dropna().unique(),
    size=mask.sum(),
    replace=True
)

# Assign random choices to missing entries
dataset.loc[mask, 'name_family_status'] = random_choices

In [ ]:
dataset['name_family_status'].value_counts()

name_family_status
married      4026
separated    4005
widow        3861
single       3858
Name: count, dtype: int64

In [ ]:
dataset.drop(['ext_source_1','ext_source_2','ext_source_3','amt_annuity_backup'], axis=1, inplace=True)

In [ ]:
dataset['name_housing_type'] = dataset['name_housing_type'].str.lower().str.replace('rented','rent')

In [ ]:
import numpy as np

mask = dataset['name_housing_type'].isna()
value_probs = dataset['name_housing_type'].value_counts(normalize=True)

random_choices = np.random.choice(
    value_probs.index,
    size=mask.sum(),
    replace=True,
    p=value_probs.values
)

dataset.loc[mask, 'name_housing_type'] = random_choices

In [ ]:
dataset['name_housing_type'].value_counts()

name_housing_type
rent        7837
owned       3980
mortgage    3933
Name: count, dtype: int64

In [ ]:
dataset['occupation_type'] = dataset['occupation_type'].str.lower()

In [ ]:
dataset['occupation_type'].value_counts()

occupation_type
laborer       2288
manager       2286
driver        2283
it staff      2219
drivr         2209
accountant    2155
Name: count, dtype: int64

In [ ]:
import numpy as np

# Create mask for missing values
mask = dataset['occupation_type'].isna()

# Randomly fill missing with existing unique values (equal probability)
random_choices = np.random.choice(
    dataset['occupation_type'].dropna().unique(),
    size=mask.sum(),
    replace=True
)

# Assign the random values to missing rows
dataset.loc[mask, 'occupation_type'] = random_choices

In [ ]:
dataset['occupation_type'].isna().sum()

np.int64(0)

In [ ]:
dataset['occupation_type'] = dataset['occupation_type'].str.replace('drivr','driver')

In [ ]:
dataset.head(5)

,customer_id,age,gender,marital_status,employment_type,annual_income,amt_credit,amt_annuity,loan_term_months,credit_score,number_of_dependents,past_defaults,loan_purpose,current_residence_years,default,name_contract_type,flag_own_car,flag_own_realty,name_income_type,name_education_type,name_family_status,name_housing_type,days_birth,days_employed,occupation_type,cnt_fam_members,region_rating_client,weekday_appr_process_start,hour_appr_process_start,organization_type
0,CUST100000,56,female,married,unemployed,50000,300000,5000.0,24.0,450,2,1,Education,16,1,cash loan,0,0,pensioner,secondary,married,owned,-11220,-13419,it staff,2,2.0,Tuesday,12,Govt
1,CUST100001,69,male,married,salaried,50000,200000,1000.0,12.0,450,0,2,Business,16,1,cash loan,1,1,working,secondary,separated,rent,-12092,-12490,driver,3,NaN,NaN,12,Med
2,CUST100002,46,other,single,salaried,100000,200000,7000.0,24.0,450,0,2,Shopping,11,1,revolving loan,0,0,businessman,secondary,single,rent,-19822,-7838,it staff,5,NaN,Wed,0,Business
3,CUST100003,32,female,widowed,unemployed,120000,300000,5000.0,12.0,450,1,0,Personal,1,1,revolving loan,0,0,pensioner,higher,single,owned,-13087,-11719,laborer,2,1.0,Wed,12,Business
4,CUST100004,60,female,single,self-employed,200000,200000,1000.0,48.0,450,3,0,Personal,2,1,cash loan,0,1,working,higher,married,owned,-24318,-545,accountant,4,NaN,NaN,NaN,Govt

In [ ]:
import numpy as np

# Identify NaN values
mask = dataset['region_rating_client'].isna()

# Randomly assign 1, 2, or 3 to those NaNs
dataset.loc[mask, 'region_rating_client'] = np.random.choice([1, 2, 3], size=mask.sum(), replace=True)

In [ ]:
dataset['weekday_appr_process_start'].value_counts()

weekday_appr_process_start
Tuesday    2749
Friday     2645
Thur       2612
Mon        2553
Wed        2526
Name: count, dtype: int64

In [ ]:
# Create mapping dictionary
weekday_mapping = {
    'mon': 'monday',
    'tue': 'tuesday',
    'tues': 'tuesday',
    'wed': 'wednesday',
    'thu': 'thursday',
    'thurs': 'thursday',
    'fri': 'friday',
    'sat': 'saturday',
    'sun': 'sunday',
    'thur':'thursday'
}

In [ ]:
# Convert to lowercase and strip spaces first
dataset['weekday_appr_process_start'] = dataset['weekday_appr_process_start'].str.lower().str.strip()

# Replace abbreviations with full names
dataset['weekday_appr_process_start'] = dataset['weekday_appr_process_start'].replace(weekday_mapping)

In [ ]:
dataset['weekday_appr_process_start'].value_counts()

weekday_appr_process_start
tuesday      2749
friday       2645
thursday     2612
monday       2553
wednesday    2526
Name: count, dtype: int64

In [ ]:
import numpy as np

mask = dataset['weekday_appr_process_start'].isna()

dataset.loc[mask, 'weekday_appr_process_start'] = np.random.choice(
    ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
    size=mask.sum(),
    replace=True
)

In [ ]:
import numpy as np

mask = dataset['hour_appr_process_start'].isna()

dataset.loc[mask, 'hour_appr_process_start'] = np.random.randint(0, 24, size=mask.sum())

In [ ]:
dataset['hour_appr_process_start'].dtype

dtype('O')

In [ ]:
dataset['hour_appr_process_start'] = dataset['hour_appr_process_start'].str.replace('?','0')

In [ ]:
import numpy as np

# Step 1: Fill missing values with random valid hours (0–23)
mask = dataset['hour_appr_process_start'].isna()
dataset.loc[mask, 'hour_appr_process_start'] = np.random.randint(0, 24, size=mask.sum())

# Step 2: Convert column to integer safely
dataset['hour_appr_process_start'] = dataset['hour_appr_process_start'].astype(int)

In [ ]:
def categorize_hour(hour):
    if 5 <= hour < 12:
        return 'morning'
    elif 12 <= hour < 17:
        return 'afternoon'
    elif 17 <= hour < 21:
        return 'evening'
    else:
        return 'night'

dataset['hour_category'] = dataset['hour_appr_process_start'].apply(categorize_hour)

In [ ]:
dataset['organization_type'] = dataset['organization_type'].str.lower().str.replace('med','medical')

In [ ]:
dataset[['date_of_birth','age']].head(10)

  date_of_birth  age
0    1995-02-19   30
1    1992-09-30   33
2    1971-08-02   54
3    1990-01-09   35
4    1959-04-11   66
5    1974-10-09   51
6    1971-07-26   54
7    1993-04-07   32
8    1968-08-16   57
9    1984-03-07   41

In [ ]:
import pandas as pd
from datetime import datetime, timedelta

# Step 1: Ensure both columns are numeric
dataset['days_birth'] = pd.to_numeric(dataset['days_birth'], errors='coerce')
dataset['age'] = pd.to_numeric(dataset['age'], errors='coerce')

# Step 2: Get today's date
today = pd.Timestamp.now().normalize()  # normalized to midnight

# Step 3: Convert days_birth into date_of_birth
# (days_birth is negative, so we add it to today's date)
dataset['date_of_birth'] = today + pd.to_timedelta(dataset['days_birth'], unit='D')

# Step 4: Optional — sanity check (verify the conversion matches 'age')
dataset['calculated_age'] = ((today - dataset['date_of_birth']).dt.days / 365).astype(int)

# Step 5: Compare a few values
print(dataset[[ 'age',  'date_of_birth']].head())

In [ ]:
dataset[['date_of_birth','age']].head(5)

  date_of_birth  age
0    1995-02-19   30
1    1992-09-30   33
2    1971-08-02   54
3    1990-01-09   35
4    1959-04-11   66

In [ ]:
dataset.drop('age', axis=1, inplace=True)

In [ ]:
# Get the list of columns
cols = list(dataset.columns)

# Find the positions of customer_id and gender
pos_customer = cols.index('customer_id')
pos_gender = cols.index('gender')

# Remove the columns if they already exist elsewhere
cols.remove('date_of_birth')
cols.remove('calculated_age')

# Insert 'days_birth' and 'calculated_age' between them
cols.insert(pos_gender, 'calculated_age')
cols.insert(pos_gender, 'date_of_birth')

# Reorder the DataFrame
dataset = dataset[cols]

In [ ]:
dataset.drop('days_birth', axis=1, inplace=True)

In [ ]:
dataset.rename(columns={'calculated_age': 'age'}, inplace=True)

In [ ]:
dataset.drop('hour_appr_process_start', axis=1, inplace=True)

In [ ]:
import pandas as pd

# Ensure numeric
dataset['days_employed'] = pd.to_numeric(dataset['days_employed'], errors='coerce')

# Get today's date
today = pd.Timestamp.now().normalize()

# Create employment start date (days_employed can be negative)
dataset['employment_start_date'] = today + pd.to_timedelta(dataset['days_employed'], unit='D')

In [ ]:
dataset['years_employed'].head(5)

0    36
1    34
2    21
3    32
4     1
Name: years_employed, dtype: int64

In [ ]:
dataset['years_employed'] = ((today - dataset['employment_start_date']).dt.days / 365).astype(int)

In [ ]:
dataset.drop('days_employed', axis=1, inplace=True)

In [ ]:
dataset.drop('employment_start_date', axis=1, inplace=True)

In [ ]:
# We'll assume your column is named 'years_employed'
# If you renamed it to 'employment_years', replace the name below

cols = list(dataset.columns)

# Remove it first (if it exists somewhere else)
if 'years_employed' in cols:
    cols.remove('years_employed')

# Insert between index 23 (occupation_type) and 24 (cnt_family_members)
cols.insert(24, 'years_employed')

# Reorder the DataFrame
dataset = dataset[cols]

In [ ]:
dataset.head(5)

,customer_id,gender,date_of_birth,age,marital_status,employment_type,annual_income,amt_credit,amt_annuity,loan_term_months,credit_score,number_of_dependents,past_defaults,loan_purpose,current_residence_years,default,name_contract_type,flag_own_car,flag_own_realty,name_income_type,name_education_type,name_family_status,name_housing_type,occupation_type,years_employed,cnt_fam_members,region_rating_client,organization_type,hour_category
0,CUST100000,female,1995-02-19,30,married,unemployed,50000,300000,5000.0,24.0,450,2,1,Education,16,1,cash loan,0,0,pensioner,secondary,married,owned,it staff,36,2,2.0,govt,afternoon
1,CUST100001,male,1992-09-30,33,married,salaried,50000,200000,1000.0,12.0,450,0,2,Business,16,1,cash loan,1,1,working,secondary,separated,rent,driver,34,3,1.0,medical,afternoon
2,CUST100002,other,1971-08-02,54,single,salaried,100000,200000,7000.0,24.0,450,0,2,Shopping,11,1,revolving loan,0,0,businessman,secondary,single,rent,it staff,21,5,3.0,business,night
3,CUST100003,female,1990-01-09,35,widowed,unemployed,120000,300000,5000.0,12.0,450,1,0,Personal,1,1,revolving loan,0,0,pensioner,higher,single,owned,laborer,32,2,1.0,business,afternoon
4,CUST100004,female,1959-04-11,66,single,self-employed,200000,200000,1000.0,48.0,450,3,0,Personal,2,1,cash loan,0,1,working,higher,married,owned,accountant,1,4,1.0,govt,afternoon

In [ ]:
dataset.to_csv("Cleaned_Bank_Data_Final.csv", index=False)